### ISSUE TITLE
Create prescriptions on projects quality using GitHub Insights

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/prescriptions#18659]
**Is your feature request related to a problem? Please describe.**

We could use the information present in the [Insights](https://github.com/thoth-station/prescriptions/pulse) section of projects GitHub repositories to get information about a project's activity and assess its quality. 

**Describe the solution you'd like**

- [ ] Get Insights information such as pulse, contributions, etc via the GitHub API
- [ ] Generate prescriptions for projects with Insights computing a score for the project on each category and eventually giving the project an overall score

**Comment by goern** [comment]
Cc: @cdolfi

**Comment by cdolfi** [comment]
@fridex I think it would be great to discuss over a call. Then we can discuss what "consumable form" means in this case and I can give a better view on whats available now and what will be in the foreseeable future
