### ISSUE TITLE
[SPIKE]Investigate Scorecards prescriptions with low confidence

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/prescriptions#25118]
**Describe the bug**

Following the update of the Scorecards handler according to the new BigQuery dataset schema, most Scorecards prescription updates (maybe even all) have been deletions caused by the corresponding entry marked as having a low confidence.
However, no prescriptions on already existing projects were updated or created.

It would be useful to investigate on the cause of this problem. A first guess is that this could be caused by either a large number of entries with low confidence in the new dataset version, or by an error in the handler logic.

**To Reproduce**

See last Scorecard prescriptions generated (last 2-3 prescription-refresh-jobs).

**Expected behavior**

New Scorecards prescriptions with high or moderate confidence are generated.

**Comment by Gkrumbach07** [comment]
The latest prescription has confidence of `0` across _all_ repos and hasnt been updated since the last entry on `2022-05-16`

<img width="777" alt="image" src="https://user-images.githubusercontent.com/12587674/188183097-aacf5555-7199-4a47-9d07-33235cee6523.png">
