### ISSUE TITLE
[2pt] Check if Thoth users are affected by `keep` package dependencies

### ISSUE THREAD

**Issue by fridex** [thoth-station/prescriptions#25117]
**Is your feature request related to a problem? Please describe.**

See: https://www.bleepingcomputer.com/news/security/pypi-package-keep-mistakenly-included-a-password-stealer/

**Describe the solution you'd like**

- [x] check if keep package is available in Thoth recommendations
- [x] write prescriptions to fix keep's dependency issues
- [x] check if Thoth's database keeps `request` package

**Comment by codificat** [comment]
> * [ ]  check if keep package is available in Thoth recommendations

The `keep` package is not in Thoth's database:

```
$ http 'https://khemenu.thoth-station.ninja/api/v1/python/package/versions?name=keep'
HTTP/1.1 404 NOT FOUND
access-control-allow-origin: *
cache-control: private
content-length: 179
content-type: application/json
date: Thu, 30 Jun 2022 12:27:18 GMT
server: gunicorn
set-cookie: 99770cb82864be05282857f803e02327=71283d09b941169601817f89b67f6781; path=/; HttpOnly; Secure; SameSite=None
x-thoth-search-ui-url: https://thoth-station.ninja/search/
x-thoth-version: 0.35.2
x-user-api-service-version: 0.35.2+messaging.0.16.1.storages.0.72.1.common.0.36.2.python.0.16.10

{
    "error": "Package 'keep' not found",
    "parameters": {
        "name": "keep",
        "order_by": null,
        "os_name": null,
        "os_version": null,
        "python_version": null
    }
}
```

However, there are prescriptions about it: https://github.com/thoth-station/prescriptions/blob/c341a4a3d55e0014f3e4f2648bf93d6458ffbfcd/prescriptions/ke_/keep/

I did a quick search to try to understand why prescriptions are there for this package we don't know about, and it seems to have originated in https://github.com/thoth-station/prescriptions/pull/42

I guess it still makes sense to add a prescription about this issue?

On the other hand, the other 2 packages mentioned in the blog post that are affected by the same situation ('pyanxdns,' and 'api-res-py') are not known to Thoth, and we don't have prescriptions about them. I guess we can leave these two out.

**Comment by codificat** [comment]
>  check if Thoth's database keeps request package

It does not:

```
$ http 'https://khemenu.thoth-station.ninja/api/v1/python/package/versions?name=request'
HTTP/1.1 404 NOT FOUND
access-control-allow-origin: *
cache-control: private
content-length: 185
content-type: application/json
date: Thu, 30 Jun 2022 13:08:37 GMT
server: gunicorn
set-cookie: 99770cb82864be05282857f803e02327=71283d09b941169601817f89b67f6781; path=/; HttpOnly; Secure; SameSite=None
x-thoth-search-ui-url: https://thoth-station.ninja/search/
x-thoth-version: 0.35.2
x-user-api-service-version: 0.35.2+messaging.0.16.1.storages.0.72.1.common.0.36.2.python.0.16.10

{
    "error": "Package 'request' not found",
    "parameters": {
        "name": "request",
        "order_by": null,
        "os_name": null,
        "os_version": null,
        "python_version": null
    }
}
```

**Comment by mayaCostantini** [comment]
Following the discussion in the last meeting, it is fine if prescriptions and packages present in Thoth's database are not correlated.

> I guess it still makes sense to add a prescription about this issue?

Yes, I guess this would still be useful if the package is ingested by Thoth someday. Feel free to create the corresponding prescription if you have time :+1:
