### ISSUE TITLE
jupyterlab does not render images with plotly and fails raising error

### ISSUE THREAD

**Issue by pacospace** [thoth-station/prescriptions#4]
**Is your feature request related to a problem? Please describe.**
I'm working with notebooks from jupyterlab and I'm using plotly to plot, but images are not shown in the jupyterlab notebook. 

It appears to be a problem of missing dependency (nbformat) in the kernel created for my notebook. https://github.com/plotly/plotly.py/issues/2159.

```
ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed
```

This dependency is not required by the stack itself, but by jupyterlab to show the images. Adding nbformat to the kernel seems to solve the problem. 

**Describe the solution you'd like**
I would like to receive a recommendation when I use plotly that warns me about missing nbformat if I'm working with jupyterlab.

**Describe alternatives you've considered**

**Additional context**

**Comment by fridex** [comment]
> **Describe the solution you'd like**
> I would like to receive a recommendation when I use plotly that warns me about missing nbformat if I'm working with jupyterlab.

We can add such recommendations. It would be great to know that jupyterhub is used by sending related data from jupyterlab-requirements extension. See https://github.com/thoth-station/adviser/issues/1514 for more info.

/remove-lifecycle rotten

**Comment by pacospace** [comment]
> > **Describe the solution you'd like**
> > I would like to receive a recommendation when I use plotly that warns me about missing nbformat if I'm working with jupyterlab.
> 
> We can add such recommendations. It would be great to know that jupyterhub is used by sending related data from jupyterlab-requirements extension. See [thoth-station/adviser#1514](https://github.com/thoth-station/adviser/issues/1514) for more info.
> 
> /remove-lifecycle rotten

In this case, do we want to know if the extension is running in JH? Should we send this information through labels?

**Comment by fridex** [comment]
> > > **Describe the solution you'd like**
> > > I would like to receive a recommendation when I use plotly that warns me about missing nbformat if I'm working with jupyterlab.
> > 
> > 
> > We can add such recommendations. It would be great to know that jupyterhub is used by sending related data from jupyterlab-requirements extension. See [thoth-station/adviser#1514](https://github.com/thoth-station/adviser/issues/1514) for more info.
> > /remove-lifecycle rotten
> 
> In this case, do we want to know if the extension is running in jupyterlab? Should we send this information through labels? Actually we submit the integration type (JUPYTER_NOTEBOOK), to know we are running from jupyter project.

Information about jupyterlab should be sent - it is a runtime environment for which we are resolving. See https://github.com/thoth-station/jupyterlab-requirements/issues/322
