### ISSUE TITLE
Introduce prescription for numpy and Pillow issue at runtime

### ISSUE THREAD

**Issue by pacospace** [thoth-station/prescriptions#48]
**Is your feature request related to a problem? Please describe.**
Issue happening at runtime: https://github.com/thoth-station/ps-cv/issues/16

Source of the issue: https://github.com/python-pillow/Pillow/issues/5571

**Describe the solution you'd like**
Thoth resolves stack correctly suggesting correct version of Pillow. `pillow==8.2.0` or `pillow>8.3.0`

**Describe alternatives you've considered**

**Additional context**

**Comment by fridex** [comment]
Done in https://github.com/thoth-station/prescriptions/pull/53
