### ISSUE TITLE
Some links to RPM packages are broken

### ISSUE THREAD

**Issue by fridex** [thoth-station/prescriptions#59]
**Describe the bug**

Check for example following RPM package and the corresponding pipeline unit that tries to link to the RPM:

https://github.com/thoth-station/prescriptions/blob/4c3a2433f7ece117e01b4dcb2c7e0e4a3e00ffef/prescriptions/cm_/cmigemo/f34_rpm.yaml#L19-L20

The pipeline unit correctly detects [cmigemo package from PyPI](https://pypi.org/project/cmigemo/) being packaged as an RPM and available as `python3-cmigemo` package:

```console
(f34) $ dnf search python3-cmigemo
============================ Name Exactly Matched: python3-cmigemo ============================
python3-cmigemo.noarch : A pure python binding for C/Migemo
```

However, the link to fedora RPM is broken:

https://src.fedoraproject.org/rpms/python3-cmigemo

The correct one is (note without "3"):

https://src.fedoraproject.org/rpms/python-cmigemo

This can be seen in some other packages as well.

**Comment by fridex** [comment]
CC @frenzymadness could you please have a look at this? You might have the required knowledge here.

Basically, we want to link to some site stating RPM information for Python RPMs packaged in Fedora34 and UBI8, but it looks like we cannot construct URLs automatically to src.fedoraproject.org just based on RPM package name for all the RPMs we found in the distribution. Thanks in advance!

**Comment by frenzymadness** [comment]
Will do next week.

**Comment by frenzymadness** [comment]
What you are looking for is the name of the source package (SRPM) because that is what you need for the URL for src.fp.org. You can get the value from a repoquery:
```
dnf repoquery --repo=rawhide --source python3-cmigemo       
Invalid configuration value: failovermethod=priority in /etc/yum.repos.d/teamviewer.repo; Configuration: OptionBinding with id "failovermethod" does not exist
Last metadata expiration check: 2:44:51 ago on Mon 19 Jul 2021 11:26:15 AM CEST.
python-cmigemo-0.1.6-21.fc35.src.rpm
```
Note there is a very simple script `pkgname` that can remove the version, release, etc. from the name:
```
dnf repoquery --repo=rawhide --source python3-cmigemo | pkgname
Invalid configuration value: failovermethod=priority in /etc/yum.repos.d/teamviewer.repo; Configuration: OptionBinding with id "failovermethod" does not exist
Last metadata expiration check: 2:44:58 ago on Mon 19 Jul 2021 11:26:15 AM CEST.
python-cmigemo
```
Or, if you have the RPM installed or you have the direct access to the RPM file, you can use the `rpm` command for this:
```
rpm -q --queryformat="%{SOURCERPM}" python3-rpkg 
rpkg-1.62-6.fc34.src.rpm
```
or
```
rpm -q --queryformat="%{SOURCERPM}" ./Packages/PyYAML/results_PyYAML/5.1.2/3.fc32/python3-pyyaml-5.1.2-3.fc32.x86_64.rpm
PyYAML-5.1.2-3.fc32.src.rpm
```
Let me know if I can help you more.

**Comment by fridex** [comment]
@frenzymadness thanks a lot, looks like this works. I will update links shortly in a PR. 👍🏻 

When it comes to UBI8/RHEL RPM packages, what would be the best site to point users to? I'm looking for something similar to src.fedoraproject.org described above.

**Comment by fridex** [comment]
> When it comes to UBI8/RHEL RPM packages, what would be the best site to point users to? I'm looking for something similar to src.fedoraproject.org described above.

Will reopen to wait, waiting for the answer if we could provide a better UX.

**Comment by frenzymadness** [comment]
I'm afraid that there is nothing like src.fedoraproject.org for RHEL 8 or UBI 8. The closest alternative might be https://access.redhat.com/downloads/content/package-browser but it requires login with a developer account and I'm afraid that there is no way how to create a direct package specific URL address.

For RHEL 9, it will be possible to link to the CentOS stream repositories on gitlab.

**Comment by fridex** [comment]
OK, thanks Lumir for your valuable input. I think we can close this for now. Thanks again. 👍🏻 

/close
