### ISSUE TITLE
Add project administrators/contributors to CODEOWNERS file

### ISSUE THREAD

**Issue by fridex** [thoth-station/prescriptions#75]
**Is your feature request related to a problem? Please describe.**

As an open-source project maintainer and/or contributor, I would like to be notified about new prescriptions generated/created by Thoth.

For this purpose, I would like to be stated in [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners#codeowners-syntax) file so that GitHub automatically asks me for a review.

**Describe the solution you'd like**

Scan all the projects we have for top contributors and maintainers and add them to the CODEOWNERS file.

**Comment by goern** [comment]
Our workflow is based on Prow's behaviour and the use of `/OWNERS`, and based on that https://github.com/kubernetes/test-infra/tree/master/prow/plugins/blunderbuss will assign reviewers. 

Is this a general request to migrate to a github based workflow for assigning reviewers, or is using CODEOWNERS an implementation detail that could also be implemented via OWNERS?

**Comment by fridex** [comment]
> Is this a general request to migrate to a github based workflow for assigning reviewers, or is using CODEOWNERS an implementation detail that could also be implemented via OWNERS?

This was just an idea of how to notify open-source package maintainers about prescriptions related to packages they maintain. If a package maintainer `X` maintains project `Y`, she/he could add himself/herself to the `CODEOWNERS` file:

```
prescriptions/Y/*  @X
```

In that case, maintainer `X` would be notified of any change in prescriptions related to `Y` and can add suggestions without being bothered by other pull requests for projects he/she is not interested in.

Is that something reasonable to do?
