### ISSUE TITLE
Automatically validate prescriptions on a pull request

### ISSUE THREAD

**Issue by fridex** [thoth-station/prescriptions#8]
**Is your feature request related to a problem? Please describe.**

I, as Thoth contributor, would like to submit an adjustment to the `prescription.yaml` file based on my observation on software I use so that Thoth will make better recommendations on the software. To make sure the change is applicable and can be accepted, CI should run `thoth-adviser validate-prescription prescription.yaml` and report back any issues spotted in the prescription file. This way we will make sure the prescription file is valid and can be used in a deployment.

**Describe the solution you'd like**

Have a CI run that runs `thoth-adviser validate-prescription prescription.yaml` with the most recent adviser container image built by AICoE-CI.

Related: https://github.com/thoth-station/adviser/pull/1781

**Comment by goern** [comment]
This sounds like a tiny python script we can wrap up as a Tekton task and a Prow job, right?


l

**Comment by fridex** [comment]
> This sounds like a tiny python script we can wrap up as a Tekton task and a Prow job, right?
> 
> /label hacktoberfest
> /label good first issue

Yes, exactly. We might eventually create a workflow that makes sure the prescription is valid when updating it in a deployment.

**Comment by fridex** [comment]
/triage accepted
/remove-lifecycle rotten
/reopen

This would be nice to have if we plan to accept new PRs from the community.

**Comment by mayaCostantini** [comment]
**Note:** when validating prescriptions, we should make sure there are no conflicts regarding the `wraps: -name` section. All packages do not use the convention of naming their versions with three numbers separated by dots (e.g. `x.y.z`) which could eventually cause different versions of a same package to have the same names. 

Example: some package version `2.3.0` could have the same name in `wraps: -name` than its `23.0` version (package name + `230`) if the package version naming is inconsistent.

**Comment by VannTen** [comment]
As an alternative to a new CI job, could this be a pre-commit hook ? This would have the advantages that it would be easily run locally. (the recent changes of pre-commit removing `--all-files` should ensure we don't validate everything every time)
